name: Publish Scraping to PyPI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'scraping/**' # Trigger only on changes within this subdirectory


jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: terraform # If using an
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel twine

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        working-directory: ./scraping
        run: |
          python -m build
          twine check dist/*
          twine upload dist/*
